// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: driver/v1/driver.proto

package driverv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunRecord_State int32

const (
	RunRecord_STATE_UNSPECIFIED RunRecord_State = 0
	RunRecord_STATE_RUNNING     RunRecord_State = 1
	RunRecord_STATE_FINISHED    RunRecord_State = 2
)

// Enum value maps for RunRecord_State.
var (
	RunRecord_State_name = map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "STATE_RUNNING",
		2: "STATE_FINISHED",
	}
	RunRecord_State_value = map[string]int32{
		"STATE_UNSPECIFIED": 0,
		"STATE_RUNNING":     1,
		"STATE_FINISHED":    2,
	}
)

func (x RunRecord_State) Enum() *RunRecord_State {
	p := new(RunRecord_State)
	*p = x
	return p
}

func (x RunRecord_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RunRecord_State) Descriptor() protoreflect.EnumDescriptor {
	return file_driver_v1_driver_proto_enumTypes[0].Descriptor()
}

func (RunRecord_State) Type() protoreflect.EnumType {
	return &file_driver_v1_driver_proto_enumTypes[0]
}

func (x RunRecord_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RunRecord_State.Descriptor instead.
func (RunRecord_State) EnumDescriptor() ([]byte, []int) {
	return file_driver_v1_driver_proto_rawDescGZIP(), []int{0, 0}
}

type RunRecord struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Version int64                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	State   RunRecord_State        `protobuf:"varint,2,opt,name=state,proto3,enum=driver.v1.RunRecord_State" json:"state,omitempty"`
	// When the run finished.
	FinishedAt    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunRecord) Reset() {
	*x = RunRecord{}
	mi := &file_driver_v1_driver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunRecord) ProtoMessage() {}

func (x *RunRecord) ProtoReflect() protoreflect.Message {
	mi := &file_driver_v1_driver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunRecord.ProtoReflect.Descriptor instead.
func (*RunRecord) Descriptor() ([]byte, []int) {
	return file_driver_v1_driver_proto_rawDescGZIP(), []int{0}
}

func (x *RunRecord) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *RunRecord) GetState() RunRecord_State {
	if x != nil {
		return x.State
	}
	return RunRecord_STATE_UNSPECIFIED
}

func (x *RunRecord) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_driver_v1_driver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driver_v1_driver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_driver_v1_driver_proto_rawDescGZIP(), []int{1}
}

type StatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Absent if this sandbox has never started a run.
	Run           *RunRecord `protobuf:"bytes,1,opt,name=run,proto3,oneof" json:"run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_driver_v1_driver_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_driver_v1_driver_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_driver_v1_driver_proto_rawDescGZIP(), []int{2}
}

func (x *StatusResponse) GetRun() *RunRecord {
	if x != nil {
		return x.Run
	}
	return nil
}

// RunSpec carries everything the driver reads from its flags and its
// environment today.
type RunSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Passed to setup commands and the agent CLI. Not set on the driver
	// process itself.
	Env map[string]string `protobuf:"bytes,5,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Workspace secrets. Added to the run's env and masked in shipped log
	// chunks.
	Secrets map[string]string `protobuf:"bytes,6,rep,name=secrets,proto3" json:"secrets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// The task to run. The driver fetches it from server_url.
	TaskId int64 `protobuf:"varint,8,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// The gritz server the driver reports to.
	ServerUrl string `protobuf:"bytes,9,opt,name=server_url,json=serverUrl,proto3" json:"server_url,omitempty"`
	// The task token used to call server_url. Masked in shipped log chunks.
	Token         string `protobuf:"bytes,10,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunSpec) Reset() {
	*x = RunSpec{}
	mi := &file_driver_v1_driver_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunSpec) ProtoMessage() {}

func (x *RunSpec) ProtoReflect() protoreflect.Message {
	mi := &file_driver_v1_driver_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunSpec.ProtoReflect.Descriptor instead.
func (*RunSpec) Descriptor() ([]byte, []int) {
	return file_driver_v1_driver_proto_rawDescGZIP(), []int{3}
}

func (x *RunSpec) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *RunSpec) GetSecrets() map[string]string {
	if x != nil {
		return x.Secrets
	}
	return nil
}

func (x *RunSpec) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *RunSpec) GetServerUrl() string {
	if x != nil {
		return x.ServerUrl
	}
	return ""
}

func (x *RunSpec) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type RunRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Version int64                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// Set to start a run. Omitted to attach.
	Spec          *RunSpec `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunRequest) Reset() {
	*x = RunRequest{}
	mi := &file_driver_v1_driver_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunRequest) ProtoMessage() {}

func (x *RunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driver_v1_driver_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunRequest.ProtoReflect.Descriptor instead.
func (*RunRequest) Descriptor() ([]byte, []int) {
	return file_driver_v1_driver_proto_rawDescGZIP(), []int{4}
}

func (x *RunRequest) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *RunRequest) GetSpec() *RunSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type RunResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*RunResponse_Accepted
	//	*RunResponse_KeepAlive
	//	*RunResponse_Finished
	Event         isRunResponse_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunResponse) Reset() {
	*x = RunResponse{}
	mi := &file_driver_v1_driver_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunResponse) ProtoMessage() {}

func (x *RunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_driver_v1_driver_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunResponse.ProtoReflect.Descriptor instead.
func (*RunResponse) Descriptor() ([]byte, []int) {
	return file_driver_v1_driver_proto_rawDescGZIP(), []int{5}
}

func (x *RunResponse) GetEvent() isRunResponse_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *RunResponse) GetAccepted() *Accepted {
	if x != nil {
		if x, ok := x.Event.(*RunResponse_Accepted); ok {
			return x.Accepted
		}
	}
	return nil
}

func (x *RunResponse) GetKeepAlive() *KeepAlive {
	if x != nil {
		if x, ok := x.Event.(*RunResponse_KeepAlive); ok {
			return x.KeepAlive
		}
	}
	return nil
}

func (x *RunResponse) GetFinished() *Finished {
	if x != nil {
		if x, ok := x.Event.(*RunResponse_Finished); ok {
			return x.Finished
		}
	}
	return nil
}

type isRunResponse_Event interface {
	isRunResponse_Event()
}

type RunResponse_Accepted struct {
	// First message on every stream.
	Accepted *Accepted `protobuf:"bytes,2,opt,name=accepted,proto3,oneof"`
}

type RunResponse_KeepAlive struct {
	KeepAlive *KeepAlive `protobuf:"bytes,3,opt,name=keep_alive,json=keepAlive,proto3,oneof"`
}

type RunResponse_Finished struct {
	// Last message of a run. Sent after its terminal runner event.
	Finished *Finished `protobuf:"bytes,6,opt,name=finished,proto3,oneof"`
}

func (*RunResponse_Accepted) isRunResponse_Event() {}

func (*RunResponse_KeepAlive) isRunResponse_Event() {}

func (*RunResponse_Finished) isRunResponse_Event() {}

type Accepted struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True if the call attached to an existing run rather than starting one.
	Attached      bool `protobuf:"varint,1,opt,name=attached,proto3" json:"attached,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Accepted) Reset() {
	*x = Accepted{}
	mi := &file_driver_v1_driver_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Accepted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Accepted) ProtoMessage() {}

func (x *Accepted) ProtoReflect() protoreflect.Message {
	mi := &file_driver_v1_driver_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Accepted.ProtoReflect.Descriptor instead.
func (*Accepted) Descriptor() ([]byte, []int) {
	return file_driver_v1_driver_proto_rawDescGZIP(), []int{6}
}

func (x *Accepted) GetAttached() bool {
	if x != nil {
		return x.Attached
	}
	return false
}

type Finished struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Version int64                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// True if the server acknowledged the run's terminal runner event.
	Reported      bool `protobuf:"varint,2,opt,name=reported,proto3" json:"reported,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Finished) Reset() {
	*x = Finished{}
	mi := &file_driver_v1_driver_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Finished) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Finished) ProtoMessage() {}

func (x *Finished) ProtoReflect() protoreflect.Message {
	mi := &file_driver_v1_driver_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Finished.ProtoReflect.Descriptor instead.
func (*Finished) Descriptor() ([]byte, []int) {
	return file_driver_v1_driver_proto_rawDescGZIP(), []int{7}
}

func (x *Finished) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Finished) GetReported() bool {
	if x != nil {
		return x.Reported
	}
	return false
}

type KeepAlive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeepAlive) Reset() {
	*x = KeepAlive{}
	mi := &file_driver_v1_driver_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeepAlive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeepAlive) ProtoMessage() {}

func (x *KeepAlive) ProtoReflect() protoreflect.Message {
	mi := &file_driver_v1_driver_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeepAlive.ProtoReflect.Descriptor instead.
func (*KeepAlive) Descriptor() ([]byte, []int) {
	return file_driver_v1_driver_proto_rawDescGZIP(), []int{8}
}

type StopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int64                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_driver_v1_driver_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driver_v1_driver_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_driver_v1_driver_proto_rawDescGZIP(), []int{9}
}

func (x *StopRequest) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type StopResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True if a running run with this version was stopped.
	Stopped       bool `protobuf:"varint,1,opt,name=stopped,proto3" json:"stopped,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopResponse) Reset() {
	*x = StopResponse{}
	mi := &file_driver_v1_driver_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopResponse) ProtoMessage() {}

func (x *StopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_driver_v1_driver_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopResponse.ProtoReflect.Descriptor instead.
func (*StopResponse) Descriptor() ([]byte, []int) {
	return file_driver_v1_driver_proto_rawDescGZIP(), []int{10}
}

func (x *StopResponse) GetStopped() bool {
	if x != nil {
		return x.Stopped
	}
	return false
}

var File_driver_v1_driver_proto protoreflect.FileDescriptor

const file_driver_v1_driver_proto_rawDesc = "" +
	"\n" +
	"\x16driver/v1/driver.proto\x12\tdriver.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdb\x01\n" +
	"\tRunRecord\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x03R\aversion\x120\n" +
	"\x05state\x18\x02 \x01(\x0e2\x1a.driver.v1.RunRecord.StateR\x05state\x12;\n" +
	"\vfinished_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\"E\n" +
	"\x05State\x12\x15\n" +
	"\x11STATE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSTATE_RUNNING\x10\x01\x12\x12\n" +
	"\x0eSTATE_FINISHED\x10\x02\"\x0f\n" +
	"\rStatusRequest\"E\n" +
	"\x0eStatusResponse\x12+\n" +
	"\x03run\x18\x01 \x01(\v2\x14.driver.v1.RunRecordH\x00R\x03run\x88\x01\x01B\x06\n" +
	"\x04_run\"\xb5\x02\n" +
	"\aRunSpec\x12-\n" +
	"\x03env\x18\x05 \x03(\v2\x1b.driver.v1.RunSpec.EnvEntryR\x03env\x129\n" +
	"\asecrets\x18\x06 \x03(\v2\x1f.driver.v1.RunSpec.SecretsEntryR\asecrets\x12\x17\n" +
	"\atask_id\x18\b \x01(\x03R\x06taskId\x12\x1d\n" +
	"\n" +
	"server_url\x18\t \x01(\tR\tserverUrl\x12\x14\n" +
	"\x05token\x18\n" +
	" \x01(\tR\x05token\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a:\n" +
	"\fSecretsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"N\n" +
	"\n" +
	"RunRequest\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x03R\aversion\x12&\n" +
	"\x04spec\x18\x02 \x01(\v2\x12.driver.v1.RunSpecR\x04spec\"\xb3\x01\n" +
	"\vRunResponse\x121\n" +
	"\baccepted\x18\x02 \x01(\v2\x13.driver.v1.AcceptedH\x00R\baccepted\x125\n" +
	"\n" +
	"keep_alive\x18\x03 \x01(\v2\x14.driver.v1.KeepAliveH\x00R\tkeepAlive\x121\n" +
	"\bfinished\x18\x06 \x01(\v2\x13.driver.v1.FinishedH\x00R\bfinishedB\a\n" +
	"\x05event\"&\n" +
	"\bAccepted\x12\x1a\n" +
	"\battached\x18\x01 \x01(\bR\battached\"@\n" +
	"\bFinished\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x03R\aversion\x12\x1a\n" +
	"\breported\x18\x02 \x01(\bR\breported\"\v\n" +
	"\tKeepAlive\"'\n" +
	"\vStopRequest\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x03R\aversion\"(\n" +
	"\fStopResponse\x12\x18\n" +
	"\astopped\x18\x01 \x01(\bR\astopped2\xbf\x01\n" +
	"\rDriverService\x12=\n" +
	"\x06Status\x12\x18.driver.v1.StatusRequest\x1a\x19.driver.v1.StatusResponse\x126\n" +
	"\x03Run\x12\x15.driver.v1.RunRequest\x1a\x16.driver.v1.RunResponse0\x01\x127\n" +
	"\x04Stop\x12\x16.driver.v1.StopRequest\x1a\x17.driver.v1.StopResponseB=Z;github.com/gritzapp/gritz/internal/proto/driver/v1;driverv1b\x06proto3"

var (
	file_driver_v1_driver_proto_rawDescOnce sync.Once
	file_driver_v1_driver_proto_rawDescData []byte
)

func file_driver_v1_driver_proto_rawDescGZIP() []byte {
	file_driver_v1_driver_proto_rawDescOnce.Do(func() {
		file_driver_v1_driver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_driver_v1_driver_proto_rawDesc), len(file_driver_v1_driver_proto_rawDesc)))
	})
	return file_driver_v1_driver_proto_rawDescData
}

var file_driver_v1_driver_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_driver_v1_driver_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_driver_v1_driver_proto_goTypes = []any{
	(RunRecord_State)(0),          // 0: driver.v1.RunRecord.State
	(*RunRecord)(nil),             // 1: driver.v1.RunRecord
	(*StatusRequest)(nil),         // 2: driver.v1.StatusRequest
	(*StatusResponse)(nil),        // 3: driver.v1.StatusResponse
	(*RunSpec)(nil),               // 4: driver.v1.RunSpec
	(*RunRequest)(nil),            // 5: driver.v1.RunRequest
	(*RunResponse)(nil),           // 6: driver.v1.RunResponse
	(*Accepted)(nil),              // 7: driver.v1.Accepted
	(*Finished)(nil),              // 8: driver.v1.Finished
	(*KeepAlive)(nil),             // 9: driver.v1.KeepAlive
	(*StopRequest)(nil),           // 10: driver.v1.StopRequest
	(*StopResponse)(nil),          // 11: driver.v1.StopResponse
	nil,                           // 12: driver.v1.RunSpec.EnvEntry
	nil,                           // 13: driver.v1.RunSpec.SecretsEntry
	(*timestamppb.Timestamp)(nil), // 14: google.protobuf.Timestamp
}
var file_driver_v1_driver_proto_depIdxs = []int32{
	0,  // 0: driver.v1.RunRecord.state:type_name -> driver.v1.RunRecord.State
	14, // 1: driver.v1.RunRecord.finished_at:type_name -> google.protobuf.Timestamp
	1,  // 2: driver.v1.StatusResponse.run:type_name -> driver.v1.RunRecord
	12, // 3: driver.v1.RunSpec.env:type_name -> driver.v1.RunSpec.EnvEntry
	13, // 4: driver.v1.RunSpec.secrets:type_name -> driver.v1.RunSpec.SecretsEntry
	4,  // 5: driver.v1.RunRequest.spec:type_name -> driver.v1.RunSpec
	7,  // 6: driver.v1.RunResponse.accepted:type_name -> driver.v1.Accepted
	9,  // 7: driver.v1.RunResponse.keep_alive:type_name -> driver.v1.KeepAlive
	8,  // 8: driver.v1.RunResponse.finished:type_name -> driver.v1.Finished
	2,  // 9: driver.v1.DriverService.Status:input_type -> driver.v1.StatusRequest
	5,  // 10: driver.v1.DriverService.Run:input_type -> driver.v1.RunRequest
	10, // 11: driver.v1.DriverService.Stop:input_type -> driver.v1.StopRequest
	3,  // 12: driver.v1.DriverService.Status:output_type -> driver.v1.StatusResponse
	6,  // 13: driver.v1.DriverService.Run:output_type -> driver.v1.RunResponse
	11, // 14: driver.v1.DriverService.Stop:output_type -> driver.v1.StopResponse
	12, // [12:15] is the sub-list for method output_type
	9,  // [9:12] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_driver_v1_driver_proto_init() }
func file_driver_v1_driver_proto_init() {
	if File_driver_v1_driver_proto != nil {
		return
	}
	file_driver_v1_driver_proto_msgTypes[2].OneofWrappers = []any{}
	file_driver_v1_driver_proto_msgTypes[5].OneofWrappers = []any{
		(*RunResponse_Accepted)(nil),
		(*RunResponse_KeepAlive)(nil),
		(*RunResponse_Finished)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_driver_v1_driver_proto_rawDesc), len(file_driver_v1_driver_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_driver_v1_driver_proto_goTypes,
		DependencyIndexes: file_driver_v1_driver_proto_depIdxs,
		EnumInfos:         file_driver_v1_driver_proto_enumTypes,
		MessageInfos:      file_driver_v1_driver_proto_msgTypes,
	}.Build()
	File_driver_v1_driver_proto = out.File
	file_driver_v1_driver_proto_goTypes = nil
	file_driver_v1_driver_proto_depIdxs = nil
}
