// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: driver/v1/driver.proto

package driverv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/gritzapp/gritz/internal/proto/driver/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// DriverServiceName is the fully-qualified name of the DriverService service.
	DriverServiceName = "driver.v1.DriverService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// DriverServiceStatusProcedure is the fully-qualified name of the DriverService's Status RPC.
	DriverServiceStatusProcedure = "/driver.v1.DriverService/Status"
	// DriverServiceRunProcedure is the fully-qualified name of the DriverService's Run RPC.
	DriverServiceRunProcedure = "/driver.v1.DriverService/Run"
	// DriverServiceStopProcedure is the fully-qualified name of the DriverService's Stop RPC.
	DriverServiceStopProcedure = "/driver.v1.DriverService/Stop"
)

// DriverServiceClient is a client for the driver.v1.DriverService service.
type DriverServiceClient interface {
	// Status reports that the server is up, plus the current run record.
	Status(context.Context, *v1.StatusRequest) (*v1.StatusResponse, error)
	// Run is attach-or-start, keyed on version:
	//   another Run stream already open      -> Unavailable (retry)
	//   record.version > version             -> FailedPrecondition (stale)
	//   record.version == version            -> attach, spec ignored
	//   no record / older version, idle      -> start the run (spec required,
	//                                           NotFound without one)
	//   another version running              -> Aborted (busy)
	// At most one Run stream is open at a time. The stream ends after the run's
	// Finished has been sent. A dropped or closed stream detaches and nothing
	// else: the run keeps going.
	Run(context.Context, *v1.RunRequest) (*connect.ServerStreamForClient[v1.RunResponse], error)
	// Stop gracefully stops the run with the given version: cancel the run
	// context with ErrStop (agents and setup commands SIGTERM their process
	// groups); the run reports its terminal event and sends Finished as usual.
	// A no-op if that version is not the active run.
	Stop(context.Context, *v1.StopRequest) (*v1.StopResponse, error)
}

// NewDriverServiceClient constructs a client for the driver.v1.DriverService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewDriverServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) DriverServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	driverServiceMethods := v1.File_driver_v1_driver_proto.Services().ByName("DriverService").Methods()
	return &driverServiceClient{
		status: connect.NewClient[v1.StatusRequest, v1.StatusResponse](
			httpClient,
			baseURL+DriverServiceStatusProcedure,
			connect.WithSchema(driverServiceMethods.ByName("Status")),
			connect.WithClientOptions(opts...),
		),
		run: connect.NewClient[v1.RunRequest, v1.RunResponse](
			httpClient,
			baseURL+DriverServiceRunProcedure,
			connect.WithSchema(driverServiceMethods.ByName("Run")),
			connect.WithClientOptions(opts...),
		),
		stop: connect.NewClient[v1.StopRequest, v1.StopResponse](
			httpClient,
			baseURL+DriverServiceStopProcedure,
			connect.WithSchema(driverServiceMethods.ByName("Stop")),
			connect.WithClientOptions(opts...),
		),
	}
}

// driverServiceClient implements DriverServiceClient.
type driverServiceClient struct {
	status *connect.Client[v1.StatusRequest, v1.StatusResponse]
	run    *connect.Client[v1.RunRequest, v1.RunResponse]
	stop   *connect.Client[v1.StopRequest, v1.StopResponse]
}

// Status calls driver.v1.DriverService.Status.
func (c *driverServiceClient) Status(ctx context.Context, req *v1.StatusRequest) (*v1.StatusResponse, error) {
	response, err := c.status.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// Run calls driver.v1.DriverService.Run.
func (c *driverServiceClient) Run(ctx context.Context, req *v1.RunRequest) (*connect.ServerStreamForClient[v1.RunResponse], error) {
	return c.run.CallServerStream(ctx, connect.NewRequest(req))
}

// Stop calls driver.v1.DriverService.Stop.
func (c *driverServiceClient) Stop(ctx context.Context, req *v1.StopRequest) (*v1.StopResponse, error) {
	response, err := c.stop.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// DriverServiceHandler is an implementation of the driver.v1.DriverService service.
type DriverServiceHandler interface {
	// Status reports that the server is up, plus the current run record.
	Status(context.Context, *v1.StatusRequest) (*v1.StatusResponse, error)
	// Run is attach-or-start, keyed on version:
	//   another Run stream already open      -> Unavailable (retry)
	//   record.version > version             -> FailedPrecondition (stale)
	//   record.version == version            -> attach, spec ignored
	//   no record / older version, idle      -> start the run (spec required,
	//                                           NotFound without one)
	//   another version running              -> Aborted (busy)
	// At most one Run stream is open at a time. The stream ends after the run's
	// Finished has been sent. A dropped or closed stream detaches and nothing
	// else: the run keeps going.
	Run(context.Context, *v1.RunRequest, *connect.ServerStream[v1.RunResponse]) error
	// Stop gracefully stops the run with the given version: cancel the run
	// context with ErrStop (agents and setup commands SIGTERM their process
	// groups); the run reports its terminal event and sends Finished as usual.
	// A no-op if that version is not the active run.
	Stop(context.Context, *v1.StopRequest) (*v1.StopResponse, error)
}

// NewDriverServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewDriverServiceHandler(svc DriverServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	driverServiceMethods := v1.File_driver_v1_driver_proto.Services().ByName("DriverService").Methods()
	driverServiceStatusHandler := connect.NewUnaryHandlerSimple(
		DriverServiceStatusProcedure,
		svc.Status,
		connect.WithSchema(driverServiceMethods.ByName("Status")),
		connect.WithHandlerOptions(opts...),
	)
	driverServiceRunHandler := connect.NewServerStreamHandlerSimple(
		DriverServiceRunProcedure,
		svc.Run,
		connect.WithSchema(driverServiceMethods.ByName("Run")),
		connect.WithHandlerOptions(opts...),
	)
	driverServiceStopHandler := connect.NewUnaryHandlerSimple(
		DriverServiceStopProcedure,
		svc.Stop,
		connect.WithSchema(driverServiceMethods.ByName("Stop")),
		connect.WithHandlerOptions(opts...),
	)
	return "/driver.v1.DriverService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case DriverServiceStatusProcedure:
			driverServiceStatusHandler.ServeHTTP(w, r)
		case DriverServiceRunProcedure:
			driverServiceRunHandler.ServeHTTP(w, r)
		case DriverServiceStopProcedure:
			driverServiceStopHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedDriverServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedDriverServiceHandler struct{}

func (UnimplementedDriverServiceHandler) Status(context.Context, *v1.StatusRequest) (*v1.StatusResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("driver.v1.DriverService.Status is not implemented"))
}

func (UnimplementedDriverServiceHandler) Run(context.Context, *v1.RunRequest, *connect.ServerStream[v1.RunResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("driver.v1.DriverService.Run is not implemented"))
}

func (UnimplementedDriverServiceHandler) Stop(context.Context, *v1.StopRequest) (*v1.StopResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("driver.v1.DriverService.Stop is not implemented"))
}
